apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
        - name: conversor
          image: wellsud/conversao-temperatura:aula1
          ports:
            - containerPort: 8080
           
---

apiVersion: v1
kind: Service
metadata:
  name: conversor
spec:
  selector:
    app: conversor
  ports:
   - protocol: TCP
     port: 8080
     nodePort: 30000
  type: NodePort
